### ISSUE TITLE
Add Support For NBGrader 

### ISSUE THREAD

**Issue by jkuruzovich** [jupyterhub/helm-chart#47]
Hello,

I’m trying to utilize NB grader with an instance of Jupyterhub on Kubernetes, created using Helm (https://github.com/jupyterhub/helm-chart).  

I’ve rebuild the singleuser docker image to include the latest version of NB grader.

As far as I can tell, NB grader seems to be installed and functioning appropriately.  However, nbgrader requires a directory to exchange files between users that is writeable by everyone but not readable, by default /srv/nbgrader/exchange. 

Any idea how this might be possible?  My understanding is that each individual is getting customized data storage linked to their container but that there is nothing which could currently be used to connect them. 

Best,
Jason

**Comment by ryanlovett** [comment]
That is true of Google Container Engine which permits you to attach one disk to many nodes, but only one can write to that disk.

One way you could do this is via a shared filesystem like NFS.

**Comment by yuvipanda** [comment]
I don't want us to support setting up an NFS server with this helm-chart tho (we should document how to use it with a pre-existing NFS server however). They have a lot of operational overhead that you then are responsible for (one user can accidentally DoS the whole filesystem, etc) - while with the current solution most of that is taken care of by Google. The 'one-disk-per-user' is the model we should recommend long term IMO, because it's simpler + provides a lot more isolation than NFS can.

@jhamrick thoughts? Is there any way nbgrader can be modified to not require a shared file system?

**Comment by jhamrick** [comment]
Once HubShare gets implemented, we'll switch nbgrader over to using that so the file management will happen through JupyterHub rather than directly through the filesystem. I am not sure what the current timeline on that is, though.

Until then, though, no---if you want to use nbgrader to distribute and collect files, it has to have access to a shared filesystem, unfortunately 😞

**Comment by labarba** [comment]
I have been working with my university Library to install our first JupyterHub, to serve several courses in different departments. Yay! 

But after much effort by the technical staff, they were stumped with nbgrader because of this issue. We had a meeting this past week where I had to give up on my hopes of having nbgrader alongside this JupyterHub. Boo.

My student/TA and I worked out a horrendous hack, for now. We have a shared Box folder, where I've added all the students, to share the homework-release notebook with them. I synced Box on an iMac (we're mad that Box doesn't have a sync app for Ubuntu!). With a script, we created Box folders for the 52 students in the class (using the course name and username). I _manually_ had to share each folder with the specific student—they will "submit" their homework by dropping the solved notebook there. We have a Python script to collect all the files from these (shared, synced) folders in the Mac, copy them to the nbgrader directory, and grade them on a local machine. SIGH.

**Comment by jkuruzovich** [comment]
@labarba Check out Github Classroom.  Probably too late for this semester, but what I like about it is that (1) students are getting used to version control (which is often glossed over) (2) distributing assignments is really easy...You create a link and they get a custom repository. (3) Autograding with travis-CI is possible (have a proof of concept but not ready for semester.)  Would be cool to figure out how to integrate NBgrader with travis-ci so that the auto grading was possible without any collection.

**Comment by labarba** [comment]
I made a deliberate decision to keep git out of this course—they are sophomores, and have even a superficial understanding of where files are stored in a computer. I teach version control in the graduate class.

**Comment by yuvipanda** [comment]
We've merged this repository into https://github.com/jupyterhub/zero-to-jupyterhub-k8s, so have moved this issue to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/174. 

For Berkeley, we use https://github.com/data-8/nbgitpuller to distribute materials to students, and okpy.org (and gradescope with PDFs of student notebooks) for collecting them back.
